### ISSUE TITLE
conda env error

### ISSUE THREAD

**Issue by caitsimop** [SBRG/precise-db#10]
Hi there!

I'm running into an error when trying to create a conda env from the provided `environment.yml`. 

The error I'm getting is:

```
conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - numpy-base==1.11.3=py37hde5b4d6_12
  - xz==5.2.5=h7b6447c_0
  - libgfortran-ng==7.3.0=hdf63c60_0
  - pandas==0.23.4=py37h04863e7_0
  - scipy==1.2.1=py37h7c811a0_0
  - ncurses==6.2=he6710b0_0
  - openssl==1.1.1f=h7b6447c_0
  - tk==8.6.8=hbc83047_0
  - libedit==3.1.20181209=hc058e9b_0
  - libffi==3.2.1=hd88cf55_4
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - numpy==1.11.3=py37h7e9f1db_12
  - readline==8.0=h7b6447c_0
  - libgcc-ng==9.1.0=hdf63c60_0
  - zlib==1.2.11=h7b6447c_3
  - python==3.7.7=hcf32534_0_cpython
  - ld_impl_linux-64==2.33.1=h53a641e_7
  - scikit-learn==0.20.3=py37hd81dba3_0
  - mpi4py==3.0.3=py37h028fd6f_0
  - sqlite==3.31.1=h7b6447c_0
```

From looking at this [this other issue](https://github.com/conda/conda/issues/7311), I'm wondering if this could be solved on your end by adding `--no-builds` to your `conda env export` command?   (eg `conda env export --no-builds > environment.yml`)

Thanks!
Caitlin

**Comment by avsastry** [comment]
Hi Caitlin, I've updated the environment.yml file in this commit 65dd0e96fd0db218ba6825959caf547f065dd5f7. The new environment.yml file is much smaller and only contains the top-level packages to install.
