### ISSUE TITLE
Doubt on choosing the number of components

### ISSUE THREAD

**Issue by MiqG** [SBRG/precise-db#11]
Hi, first, thank you for developing such a great tool and for sharing it with the community! I am impressed by the level of insights you achieved in [Sastry *et al*. 2019](https://doi.org/10.1038/s41467-019-13483-w).

I have been using ICA for some time and it is the first time I see using PCA to set the number of components beforehand. Since the theory behind the two approaches is quite different, out of curiosity, what was your rationale in using this approach? Is there any article you could refer me to on the topic?

Thank you very much in advance, best,

Miquel

**Comment by avsastry** [comment]
Hi Miquel,

This is a very pertinent question, and we actually are in the process of writing a manuscript to detail a new empirical method to select the optimal dimensionality of expression datasets. 

We initially used PCA to set the number of components as it was the simplest metric described in the review by [Kong et al.](https://pubmed.ncbi.nlm.nih.gov/19007336/) (See "Number Estimation of Latent Vectors"). 

We also tried a few other methods described in previous literature, but found that they did not scale effectively to noisy datasets with 100s of samples and 1000s of genes.

Please let me know if you would like to discuss this further.

Best,
Anand
