### ISSUE TITLE
log_tpm Vs. log_tpm_full, Why are specific genes different?

### ISSUE THREAD

**Issue by adirot** [SBRG/precise-db#9]
Hi!
If I understand correctly, the difference between log_tpm.csv and log_tpm_full.csv should be that noisy genes are removed from  log_tpm_full.csv to get  log_tpm.csv .

If I understand correctly, why are genes listed in both  log_tpm.csv and  log_tpm_full.csv have very different values?

example: b0002:

in log_tpm_full: 

           | control__wt_glc__1 | control__wt_glc__2 | fur__wt_dpd__1
b0002 | 2054.287 | 2238.411 | 3335.895

and in log_tpm, the same three conditions:

           | control__wt_glc__1 | control__wt_glc__2 | fur__wt_dpd__1
b0002 | 11.00665 | 11.1302 | 11.70495

 Why is that?

**Comment by avsastry** [comment]
Looks like I forgot to log-transform the log_tpm_full values. I've fixed the file in the latest commit 9509f3b8269aae5d4f3cfee0085e469684b0ca9b
